### ISSUE TITLE
[Feature Request] Jds Textarea

### ISSUE THREAD

**Issue by bangunbagustapa** [jabardigitalservice/jds-design-system-vue-lib#110]
**Apakah permintaan fitur berawal dari kesulitan penggunaan library? Coba jelaskan.**
Saya ingin melakukan customisasi pada attribute di textarea karena ada beberapa requirement dan validasi yang dibutuhkan.

**Jelaskan solusi yang anda inginkan**
Saya ingin dapat memberikan props untuk `col`, `row` dan `max length`

**Comment by Ibwedagama** [comment]
Halo @bangunbagustapa terima kasih atas feedbacknya, kami akan segera mendiskusikan hal ini bersama tim 👍🏼
