### ISSUE TITLE
Komponent select tampilan optionsnya jadi terpotong

### ISSUE THREAD

**Issue by maruf12** [jabardigitalservice/jds-design-system-vue-lib#80]
**Version**
0.0.3--beta.2

**Description**
Ketika menggunakan input select tampilan selectnya seperti gambar dibawah padahal belum diberikan style apapun.
![select-error](https://user-images.githubusercontent.com/9880869/130222343-1baa4dfd-f38d-4be2-a667-9bfc72037835.PNG)

**Actual Result**
Tampilan options terpotong.

**Expected Result**
Secara default tampilan options tidak terpotong.

**Comment by adrianpdm** [comment]
Terkait ini, perlu dilakukan pengujian terkait bagaimana behavior CSS design system ketika digabungkan dengan CSS UI library lain.

Adapun, agak sulit ya jika pengujian harus dilakukan untuk semua UI library?.

Mungkin, kita coba uji dengan CSS reset standar seperti:
- [normalize.css](https://necolas.github.io/normalize.css/)
- [sanitize.css](https://csstools.github.io/sanitize.css/).
- [modern-normalize.css](https://github.com/sindresorhus/modern-normalize) (ini adalah CSS reset yang digunakan pada TailwindCSS)

**Comment by adzharamrullah** [comment]
hallo, @maruf12 terimakasih telah memberikan isu ini.

Untuk mengatasi isu ini sangat betul sekali apa yang disampaikan oleh @adrianpdm, bahwa kami tidak merekomendasi penggabungan _library_  JDS Design System dengan _UI Libray_ yang lain. karena itu diluar jangkauan kami yang mana kami harus me-_provide_ seluruh _UI Library_ yang ada agar sesuai dengan _Library_ kami.
